export const projectsData = [
  {
    id: "01",
    thumbnail: "../../src/assets/Catering-Dual.jpg",
    websiteDesign: "../../src/assets/cateringservices.jpg",
    isWebsite: "false",
    projectName: "Catering Services Website",
    projectDetails: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed leo eros, auctor ac sagittis ut, vestibulum a ante. Duis id tellus sit amet neque hendrerit varius sed id dolor.",
    isHtml: true,
    isCss: true,
    isJs: true,
    isReact: false,
    isWordpress: false,
    isNode: false,
    isMongoDb: false,
    isFigmaLink: true,
    isWebsiteLink: true,
    websiteLink: '/',
  },
  {
    id: "02",
    thumbnail: "../../src/assets/multi-decor-dual.jpg",
    websiteDesign: "../../src/assets/homedecorstore.jpg",
    isWebsite: "true",
    projectName: "Home Decore Store",
    projectDetails: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed leo eros, auctor ac sagittis ut, vestibulum a ante. Duis id tellus sit amet neque hendrerit varius sed id dolor.",
    isHtml: false,
    isCss: false,
    isJs: false,
    isReact: false,
    isWordpress: true,
    isNode: false,
    isMongoDb: false,
    isFigmaLink: true,
    isWebsiteLink: true,
    websiteLink: '/',
  },
  {
    id: "03",
    thumbnail: "../../src/assets/multi-decor-dual.jpg",
    websiteDesign: "../../src/assets/homedecorstore.jpg",
    isWebsite: "true",
    projectName: "Home Decore Store",
    projectDetails: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed leo eros, auctor ac sagittis ut, vestibulum a ante. Duis id tellus sit amet neque hendrerit varius sed id dolor.",
    isHtml: false,
    isCss: false,
    isJs: false,
    isReact: false,
    isWordpress: true,
    isNode: false,
    isMongoDb: false,
    isFigmaLink: true,
    isWebsiteLink: true,
    websiteLink: '/',
  },
];
