export const projectsData = [
  {
    id: "01",
    thumbnail: "../../src/assets/Catering-Dual.jpg",
    websiteDesign: "../../src/assets/cateringservices.jpg",
    isWebsite: "false",
    projectName: "Catering Services Website",
    projectDetails: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed leo eros, auctor ac sagittis ut, vestibulum a ante. Duis id tellus sit amet neque hendrerit varius sed id dolor.",
    isHtml: true,
    isCss: true,
    isJs: true,
    isReact: false,
    isWordpress: false,
    isNode: false,
    isMongoDb: false,
    isFigmaLink: true,
    isWebsiteLink: true,
    websiteLink: "https://cateringservicesweb.web.app/",
    figmaLink: "https://www.figma.com/proto/rCYBGO9bCvY8CHYjmFKLZL/CATERING?page-id=0%3A1&node-id=2-2&viewport=934%2C543%2C0.45&t=4ngww9FtC2Zj8yDE-1&scaling=contain&content-scaling=fixed"
  },
  {
    id: "02",
    thumbnail: "../../src/assets/multi-decor-dual.jpg",
    websiteDesign: "../../src/assets/homedecorstore.jpg",
    isWebsite: "true",
    projectName: "Home Decore Store",
    projectDetails: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed leo eros, auctor ac sagittis ut, vestibulum a ante. Duis id tellus sit amet neque hendrerit varius sed id dolor.",
    isHtml: false,
    isCss: false,
    isJs: false,
    isReact: false,
    isWordpress: true,
    isNode: false,
    isMongoDb: false,
    isFigmaLink: true,
    isWebsiteLink: true,
    websiteLink: "http://home-decor-store.free.nf",
    figmaLink: "https://www.figma.com/proto/47NVXJR9AeGm0PN08FeX7c/MULTI-DECOR-PRODUCTS(LAWRENCE)?page-id=0%3A1&node-id=160-2&viewport=1914%2C700%2C0.1&t=b5fH877ntAGGw955-1&scaling=min-zoom&content-scaling=fixed"
  },
  {
    id: "03",
    thumbnail: "../../src/assets/CYFONII.jpg",
    websiteDesign: ../../src/assets/CYFONII.jpg,
    isWebsite: "true",
    projectName: "CYFONII",
    projectDetails: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed leo eros, auctor ac sagittis ut, vestibulum a ante. Duis id tellus sit amet neque hendrerit varius sed id dolor.",
    isHtml: false,
    isCss: false,
    isJs: false,
    isReact: false,
    isWordpress: true,
    isNode: false,
    isMongoDb: false,
    isFigmaLink: false,
    isWebsiteLink: true,
    websiteLink: "https://nftmarketplace-02.web.app",
    figmaLink: "false"
  },
];
